import type { Metadata } from "next";

import Navbar from "@/components/common/navbar/Navbar";
import Notifications from "@/components/common/notifications/Notifications";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Notifications />
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
